"""
Settings repository port. Infra implements (e.g., SQLite).
"""
from __future__ import annotations
from typing import Protocol, Optional

class SettingsRepository(Protocol):
    def get_api_key(self, provider: str) -> Optional[str]:
        ...
    def set_api_key(self, provider: str, key: str) -> None:
        ...
    def get_model(self, provider: str) -> Optional[str]:
        ...
    def set_model(self, provider: str, model: str) -> None:
        ...
    def get_theme(self) -> Optional[str]:
        ...
    def set_theme(self, theme: str) -> None:
        ...
    def get_colors_enabled(self) -> bool:
        ...
    def set_colors_enabled(self, enabled: bool) -> None:
        ...

__all__ = ["SettingsRepository"]